### ISSUE TITLE
在配置里安装报错

### ISSUE THREAD

**Issue by Soulboy1234** [shaonianzhentan/xiaomi_tv#22]
Error setting up entry 192.168.0.103 for xiaomi_tv
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/xiaomi_tv/__init__.py", line 10, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by shaonianzhentan** [comment]
已修复
